[wip]Create new group views
Tai-f/chat-space pull request #12
Opened 2016-11-22 04:46 UTC by Tai-f

#What
1. generate group views
2. configure routes

#Why
to create group views (one of the main function)

2016-11-22 08:51 UTC, hand12 reviewed
いくつかコメントしたのでご確認ください！

2016-11-22 08:51 UTC, hand12 commented on app/controllers/groups_controller.rb
> +  protected
protectedは、GroupsControllrクラスのインスタンスと、このクラスの中以外からは呼び出されないようにするものですが、似たようなものでprivateというものがあります。
こちらはこのメソッドを定義しているクラスの中でのみ呼び出すことが可能となるもので、インスタンスからは呼び出せません。
今回の場合、インスアンスから呼び出しているわけではないので、privateを使うので大丈夫です！
http://qiita.com/tbpgr/items/6f1c0c7b77218f74c63e
こちらのサイトにも載っていますので一度見てください！

2016-11-22 08:51 UTC, hand12 commented on app/controllers/groups_controller.rb
> +      params.permit( :name)
requireも使いましょう！
requireメソッドが何をしているのかと、このstrongparameterはなんのために行っているのかも調べて見てください！

2016-11-22 08:51 UTC, hand12 commented on app/views/devise/unlocks/new.html.haml
> += render "devise/shared/links"
deviseでのuserモデルを作成するのであれば、deviseの導入や、userモデルの導入のブランチでdevioseの返還も行ってください！
ブランチ名と関係ないことは基本的に避けてください。

2016-11-22 08:51 UTC, hand12 commented on app/views/groups/edit.html.haml
> +        %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/
Groupの編集昨日も入れるのであれば、ブランチ名はGroup機能の追加などにしておきましょう！
また、inputタグはform_forに直してください！

2016-11-22 08:51 UTC, hand12 commented on app/views/groups/new.html.haml
> +        %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/
こちらもですね！

2016-11-22 08:51 UTC, hand12 commented on db/migrate/20161118083706_create_messages.rb
> +      t.references   :group, foreign_key: true
indexも貼りましょう！

2016-11-22 09:00 UTC, Tai-f commented on app/controllers/groups_controller.rb
> +  protected
了解です！

2016-11-22 09:23 UTC, Tai-f commented on app/views/devise/unlocks/new.html.haml
> += render "devise/shared/links"
間違えてcommitしてしまったようです。このファイルは触っていないので、spaceなどで反映されてしまった可能性があります。以後気をつけます。

2016-11-22 09:25 UTC, Tai-f commented on app/views/groups/edit.html.haml
> +        %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/
こちらも同様にspaceなどで、反映してしまったようです。commitする際に注意深くindexに送るファイルを確認します。

2016-11-22 09:29 UTC, Tai-f commented on db/migrate/20161118083706_create_messages.rb
> +      t.references   :group, foreign_key: true
了解です！

2016-11-23 05:25 UTC, hc0208 requested changes

2016-11-23 05:25 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +    Group.create(create_params)
group名が空の時は保存されないようにモデルにバリデーションをかけましょう。
コントローラーにはgroupの作成に成功した時と失敗した時の処理を書くようにしましょう。

2016-11-23 07:07 UTC, Tai-f commented on app/controllers/groups_controller.rb
> +    Group.create(create_params)
validateについては記述しましたが、コントローラーについての記述がわかりません。
ご教授いただければ幸いです。

2016-11-23 07:25 UTC, hc0208 requested changes

2016-11-23 07:25 UTC, hc070208 commented on app/controllers/groups_controller.rb
> +    group = Group.create(create_params)
@group = Group.new(create_params)
としてあげて@group.saveが成功するのかしないのかで条件分岐してあげるのがベストです。

2016-11-23 07:25 UTC, Tai-f commented on app/controllers/groups_controller.rb
> +    group = Group.create(create_params)
了解しました。

2016-11-23 07:48 UTC, hc070208 commented
LGTM

2016-11-23 07:49 UTC, merged